version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.hsqldb:hsqldb
    versions:
    - 2.6.0
  - dependency-name: com.microsoft.sqlserver:mssql-jdbc
    versions:
    - "9.3.1.jre15-preview"
